### ISSUE TITLE
"blospot.com" always returns valid() = False

### ISSUE THREAD

**Issue by joncombe** [nacholibre/url_extract#1]
Thanks for such a useful tool. :)

I came across a weird error today purely by chance however, and it only affected one url that I could find. For some reason "blogspot.com" gives a valid() = False response. Here is an example:

```
>>> from url_extract import UrlExtract
>>> extract = UrlExtract()
>>> ex1 = extract.extract('google.com')
>>> ex1.valid()
True
>>> ex2 = extract.extract('blogspot.com')
>>> ex2.valid()
False
```

**Comment by joncombe** [comment]
`github.io` also produces the same error. More than 99% of the time the code works as expected.

**Comment by nacholibre** [comment]
Hello,

blogspot.com and github.io are actually tlds like com and net.

You can see the suffix list here: https://publicsuffix.org/list/effective_tld_names.dat

**Comment by joncombe** [comment]
Yes, you are correct, my mistake. Thank you for such a quick response, it is much appreciated.
